(((lambda (X)
    ((lambda (procedure)
       (X (lambda (arg) ((procedure procedure) arg))))
     (lambda (procedure)
       (X (lambda (arg) ((procedure procedure) arg))))))
  (lambda (func-arg)
    (lambda (n)
      ((_if (= 0 n)
           (lambda () 1)
           (lambda () (* n (func-arg (- n 1)))))))))
 5)
